### ISSUE TITLE
Crash in low memory conditions

### ISSUE THREAD

**Issue by coldfish** [bufferapp/SimpleBottomNavigation#8]
If I enable the "don't keep activities" from the Developer Options to test the low memory cases, after getting out and in via HOME button, library is crashing.. 

`java.lang.RuntimeException: Unable to start activity ComponentInfo{net.abc/net.abc.ui.MainActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: android.support.design.widget.BottomNavigationView$SavedState
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                         at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                      Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: android.support.design.widget.BottomNavigationView$SavedState
                                                                         at android.os.Parcel.readParcelableCreator(Parcel.java:2536)
                                                                         at android.os.Parcel.readParcelable(Parcel.java:2462)
                                                                         at android.view.AbsSavedState.<init>(AbsSavedState.java:67)
                                                                         at android.view.View$BaseSavedState.<init>(View.java:22746)
                                                                         at android.view.View$BaseSavedState.<init>(View.java:22735)
                                                                         at org.buffer.adaptablebottomnavigation.view.ViewSwapper$SavedState.<init>(ViewSwapper.java:179)
                                                                         at org.buffer.adaptablebottomnavigation.view.AdaptableBottomNavigationView$SavedState$1.createFromParcel(AdaptableBottomNavigationView.java:151)
                                                                         at org.buffer.adaptablebottomnavigation.view.AdaptableBottomNavigationView$SavedState$1.createFromParcel(AdaptableBottomNavigationView.java:148)
                                                                         at android.support.v4.os.ParcelableCompatCreatorHoneycombMR2.createFromParcel(ParcelableCompatHoneycombMR2.java:43) `

**Comment by mkaraoz** [comment]
I solved this problem with this line: `bottomNavigationView.setSaveEnabled(false); `
But it has side-effects; app highlights the wrong tab after coming back from sleep. If you are OK with API24 and up you can edit ViewSwapper class to call SavedState(parcel, classLoader) instead of SavedState(parcel) and it works fine.
